# Generated by Django 6.0.5 on 2026-06-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HR', 'HR Staff'), ('ACCOUNTANT', 'Accountant'), ('SUPERINTENDENT', 'Superintendent'), ('TEACHING', 'Teaching Staff'), ('NON_TEACHING', 'Non-Teaching Staff'), ('ADMINISTRATIVE', 'Administrative Staff')], default='TEACHING', max_length=20),
        ),
    ]
