# Generated by Django 6.0.5 on 2026-06-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='clearance_document',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='travel_authority_document',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
    ]
