# Generated by Django 6.0.5 on 2026-06-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_leaverequest_clearance_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='maternity_notice_allocation',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='paternity_marriage_contract',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='rehab_concurrence',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='rehab_letter_request',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='rehab_police_report',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='vawc_medical_cert',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='women_special_histopath',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='women_special_operative_technique',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
    ]
