# Generated by Django 6.0.5 on 2026-06-25 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_leaverequest_maternity_notice_allocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Immediate supervisor (e.g. Principal or Head Teacher) who gives recommending approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending_supervisor', 'Pending Immediate Supervisor / Principal'), ('pending_hr', 'Pending HR Officer'), ('pending_superintendent', 'Pending Superintendent'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_supervisor', max_length=25),
        ),
    ]
