# Generated by Django 6.0.3 on 2026-05-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_applicant_performancereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sick_leave_balance',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='vacation_leave_balance',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
    ]
