# Generated by Django 6.0.5 on 2026-06-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_supervisor_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='rejection_stage',
            field=models.CharField(blank=True, choices=[('pending_supervisor', 'Pending Immediate Supervisor / Principal'), ('pending_hr', 'Pending HR Officer'), ('pending_superintendent', 'Pending Superintendent'), ('approved', 'Approved'), ('rejected', 'Rejected')], help_text='The stage at which the request was rejected', max_length=25, null=True),
        ),
    ]
