# Generated by Django 6.0.5 on 2026-05-24 12:44

import core.models.loan
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_sick_leave_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providentloan',
            name='co_maker',
            field=models.ForeignKey(blank=True, help_text='Co-maker must have equal or higher salary grade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comaker_loans', to='core.employee'),
        ),
        migrations.AddField(
            model_name='providentloan',
            name='co_maker_name',
            field=models.CharField(blank=True, help_text='Fallback co-maker name if not in the system.', max_length=100),
        ),
        migrations.AddField(
            model_name='providentloan',
            name='letter_request',
            field=models.TextField(blank=True, help_text='Formal letter stating the purpose of the loan.'),
        ),
        migrations.AddField(
            model_name='providentloan',
            name='purpose',
            field=models.CharField(choices=[('general', 'General'), ('medical', 'Medical / Hospitalization'), ('calamity', 'Calamity'), ('educational', 'Educational'), ('emergency', 'Emergency')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='providentloan',
            name='remarks',
            field=models.TextField(blank=True, help_text='HR remarks on approval/rejection.'),
        ),
        migrations.AddField(
            model_name='providentloan',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providentloan',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='providentloan',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.employee'),
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('laf', 'Loan Application Form'), ('letter_request', 'Letter Request'), ('auth_deduct', 'Authorization to Deduct'), ('payslip', 'Payslip'), ('deped_id', 'DepEd ID'), ('appointment', 'Approved Appointment'), ('service_record', 'Updated Service Record'), ('contract', 'Contract of Service'), ('comaker_payslip', 'Co-Maker Payslip'), ('medical_abstract', 'Medical Abstract/Certificate'), ('calamity_cert', 'Calamity Certificate')], max_length=30)),
                ('file', models.FileField(upload_to='loan_documents/', validators=[core.models.loan.validate_loan_doc_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.providentloan')),
            ],
            options={
                'ordering': ['doc_type', '-uploaded_at'],
            },
        ),
    ]
