# Generated by Django 6.0.5 on 2026-05-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_providentloan_co_maker_providentloan_co_maker_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='date_released',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('released', 'Released')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR Staff'), ('SUPERVISOR', 'Supervisor'), ('ACCOUNTANT', 'Accountant'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
    ]
