# Generated by Django 6.0.5 on 2026-06-25 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_leaverequest_rejection_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='interest_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='principal_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='providentloan',
            name='date_granted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providentloan',
            name='station_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='providentloan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('released', 'Released'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
