# Generated by Django 6.0.5 on 2026-06-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_loanpayment_interest_paid_loanpayment_posted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
