# Generated by Django 6.0.5 on 2026-05-27 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payroll_date_released_payroll_status_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='sick_leave_balance',
            new_name='leave_balance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='vacation_leave_balance',
        ),
    ]
