# Generated by Django 6.0.5 on 2026-05-28 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_sick_leave_balance_employee_leave_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providentloan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('released', 'Released'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='PDSUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pds_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_avg', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pds_uploads', to='core.employee')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
