# Generated by Django 6.0.5 on 2026-09-04 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_applicantdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='demo_teaching_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Classroom Observation / Demonstration Teaching (Max 35 pts)', max_digits=5, validators=[django.core.validators.MaxValueValidator(35.0)]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='education_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Education (Max 10 pts)', max_digits=5, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='exam_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Teacher Reflection Form / Examination (Max 25 pts)', max_digits=5, validators=[django.core.validators.MaxValueValidator(25.0)]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='experience_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Experience (Max 10 pts)', max_digits=5, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='interview_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Behavioral Events Interview (Max 10 pts)', max_digits=5, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='training_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Training (Max 10 pts)', max_digits=5, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
