# Generated by Django 6.0.5 on 2026-09-04 12:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_applicant_demo_teaching_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='gsis',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GSIS 9% Life and Retirement', max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pera',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='PERA (₱1,000 semi-monthly cutoff)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='sss',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Legacy alias for GSIS', max_digits=10),
        ),
    ]
