# Generated by Django 6.0.5 on 2026-05-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_employee_agency_employee_no_employee_civil_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ELEMENTARY', 'Elementary'), ('SECONDARY', 'Secondary'), ('VOCATIONAL', 'Vocational/Trade Course'), ('COLLEGE', 'College'), ('GRADUATE', 'Graduate Studies')], max_length=20)),
                ('school_name', models.CharField(max_length=255)),
                ('degree_course', models.CharField(max_length=255)),
                ('period_from', models.CharField(blank=True, max_length=10, null=True)),
                ('period_to', models.CharField(blank=True, max_length=10, null=True)),
                ('highest_level', models.CharField(blank=True, max_length=100, null=True)),
                ('year_graduated', models.CharField(blank=True, max_length=4, null=True)),
                ('honors_received', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_exam', models.DateField(blank=True, null=True)),
                ('place_of_exam', models.CharField(blank=True, max_length=255, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('CHILD', 'Child')], max_length=10)),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('employer', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=False)),
                ('position_title', models.CharField(max_length=255)),
                ('agency', models.CharField(max_length=255)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('status_of_appointment', models.CharField(blank=True, max_length=50, null=True)),
                ('is_gov_service', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='core.employee')),
            ],
        ),
    ]
