# Generated by Django 6.0.5 on 2026-09-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_payroll_gsis_payroll_pera_alter_payroll_sss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_dtr_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], db_index=True, default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('vacation', 'Vacation Leave'), ('forced', 'Mandatory/Forced Leave'), ('sick', 'Sick Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('special_privilege', 'Special Privilege Leave'), ('solo_parent', 'Solo Parent Leave'), ('study', 'Study Leave'), ('vawc', '10-Day VAWC Leave'), ('rehabilitation', 'Rehabilitation Privilege'), ('women_special', 'Special Leave Benefits for Women'), ('emergency', 'Special Emergency (Calamity) Leave'), ('adoption', 'Adoption Leave'), ('others', 'Others')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending_supervisor', 'Pending Immediate Supervisor / Principal'), ('pending_hr', 'Pending HR Officer'), ('pending_superintendent', 'Pending Superintendent'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending_supervisor', max_length=25),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='cutoff_period',
            field=models.CharField(db_index=True, default='May 1-15, 2026', max_length=50),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('released', 'Released')], db_index=True, default='draft', max_length=10),
        ),
    ]
