# Generated by Django 6.0.5 on 2026-09-10 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_attendance_is_dtr_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='face_descriptor',
        ),
    ]
