# Generated by Django 6.0.5 on 2026-09-16 13:49

import core.models.pds
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_employee_face_descriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='doc_type',
            field=models.CharField(choices=[('laf', 'Loan Application Form'), ('letter_request', 'Letter Request'), ('auth_deduct', 'Authorization to Deduct'), ('payslip', 'Payslip'), ('deped_id', 'DepEd ID'), ('appointment', 'Approved Appointment'), ('service_record', 'Updated Service Record'), ('contract', 'Contract of Service'), ('comaker_payslip', 'Co-Maker Payslip'), ('medical_abstract', 'Medical Abstract / Certificate'), ('calamity_cert', 'Calamity Certificate')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pdsupload',
            name='file',
            field=models.FileField(upload_to='pds_uploads/', validators=[core.models.pds.validate_pds_file]),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.employee')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
