# Generated by Django 6.0.5 on 2026-05-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_education_degree_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='philsys_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='umid_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
