# Generated by Django 6.0.5 on 2026-05-31 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_employee_philsys_id_employee_umid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gsis_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='sss_no',
        ),
    ]
