# Generated by Django 6.0.5 on 2026-05-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_employee_gsis_id_remove_employee_sss_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
