# Generated by Django 6.0.5 on 2026-05-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_familymember_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='leave_balance',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='reason',
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_leave_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='vacation_leave_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_days_with_pay',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_days_without_pay',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_others',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='commutation',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('requested', 'Requested')], default='not_requested', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='disapproval_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='illness_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_in_hospital',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_monetization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_terminal_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_within_philippines',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='location_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='other_type_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='study_type',
            field=models.CharField(blank=True, choices=[('masters', "Completion of Master's Degree"), ('board_exam', 'BAR/Board Examination Review')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='working_days_applied',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('vacation', 'Vacation Leave'), ('forced', 'Mandatory/Forced Leave'), ('sick', 'Sick Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('special_privilege', 'Special Privilege Leave'), ('solo_parent', 'Solo Parent Leave'), ('study', 'Study Leave'), ('vawc', '10-Day VAWC Leave'), ('rehabilitation', 'Rehabilitation Privilege'), ('women_special', 'Special Leave Benefits for Women'), ('emergency', 'Special Emergency (Calamity) Leave'), ('adoption', 'Adoption Leave'), ('others', 'Others')], max_length=50),
        ),
    ]
