# Generated by Django 6.0.5 on 2026-05-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_employee_leave_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sick_leave_balance',
            field=models.DecimalField(decimal_places=3, default=15.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vacation_leave_balance',
            field=models.DecimalField(decimal_places=3, default=15.0, max_digits=5),
        ),
    ]
