# Generated by Django 6.0.5 on 2026-05-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_employee_sick_leave_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='education_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='applicant',
            name='exam_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='applicant',
            name='experience_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='applicant',
            name='interview_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='applicant',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_status_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='pds_file',
            field=models.FileField(blank=True, null=True, upload_to='applicant_pds/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='applicant_resumes/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='school_division',
            field=models.CharField(default='Lucena City', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='applicant',
            name='training_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied / Submitted'), ('initial_evaluation', 'Initial Evaluation (QS Check)'), ('comparative_assessment', 'Comparative Assessment (HRMPSB)'), ('interview', 'Behavioral Events Interview (BEI)'), ('background_investigation', 'Background Investigation'), ('appointment_proposed', 'For Appointment / Proposed'), ('hired', 'Appointed / Hired'), ('disqualified', 'Not Qualified (QS)'), ('rejected', 'Not Selected (CAR/RQA)')], default='applied', max_length=30),
        ),
    ]
