# Generated by Django 6.0.5 on 2026-05-31 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_applicant_education_score_applicant_exam_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='education_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='exam_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='experience_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='interview_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='position_applied',
            field=models.CharField(choices=[('Teacher I', 'Teacher I'), ('Teacher II', 'Teacher II'), ('Teacher III', 'Teacher III'), ('Master Teacher I', 'Master Teacher I'), ('Master Teacher II', 'Master Teacher II'), ('SPED Teacher I', 'SPED Teacher I'), ('Administrative Officer I', 'Administrative Officer I'), ('Administrative Officer II', 'Administrative Officer II'), ('Administrative Assistant I', 'Administrative Assistant I'), ('Administrative Assistant II', 'Administrative Assistant II'), ('Registrar I', 'Registrar I'), ('Accountant I', 'Accountant I'), ('School Principal I', 'School Principal I')], max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='training_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
