# Generated by Django 6.0.5 on 2026-06-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_applicant_education_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(default='Land Bank of the Philippines', max_length=100),
        ),
        migrations.AddField(
            model_name='payroll',
            name='days_worked',
            field=models.DecimalField(decimal_places=1, default=11.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='payroll',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
