# Generated by Django 6.0.5 on 2026-06-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_employee_account_number_employee_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_descriptor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
