# Generated by Django 6.0.5 on 2026-06-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_employee_department_alter_employee_position_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salarygrade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salarygrade',
            name='label',
            field=models.CharField(blank=True, help_text="e.g., 'Teacher I', 'Principal II'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base monthly salary. Auto-filled if Position or Salary Grade is set.', max_digits=12, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='salarygrade',
            unique_together={('grade', 'step', 'label')},
        ),
    ]
