# Generated by Django 6.0.5 on 2026-06-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_salarygrade_unique_together_salarygrade_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarygrade',
            options={'ordering': ['grade']},
        ),
        migrations.AlterUniqueTogether(
            name='salarygrade',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='grade',
            field=models.IntegerField(unique=True),
        ),
        migrations.RemoveField(
            model_name='salarygrade',
            name='step',
        ),
    ]
