# Generated by Django 6.0.5 on 2026-06-08 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_salarygrade_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='time_in',
            new_name='am_in',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='time_out',
            new_name='am_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='dtr_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='dtr_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dtrs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_dtr_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ot_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ot_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='pm_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='pm_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
