# Generated by Django 6.0.5 on 2026-06-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_time_in_attendance_am_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='e_signature',
            field=models.ImageField(blank=True, null=True, upload_to='e_signatures/'),
        ),
    ]
