# Generated by Django 6.0.5 on 2026-06-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_employee_e_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR Staff'), ('SUPERINTENDENT', 'SUPERINTENDENT'), ('ACCOUNTANT', 'Accountant'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
    ]
