# Generated by Django 6.0.5 on 2026-06-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR Staff'), ('SUPERINTENDENT', 'Superintendent'), ('SUPERVISOR', 'Supervisor'), ('ACCOUNTANT', 'Accountant'), ('TEACHING', 'Teaching Staff'), ('ADMINISTRATIVE', 'Administrative Staff'), ('NON_TEACHING', 'Non-Teaching Staff')], default='TEACHING', max_length=20),
        ),
    ]
