# Generated by Django 6.0.5 on 2026-06-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEACHING', 'Teaching Staff'), ('ADMINISTRATIVE', 'Administrative Staff'), ('NON_TEACHING', 'Non-Teaching Staff'), ('HR', 'HR Staff')], default='TEACHING', max_length=20),
        ),
    ]
