# Generated by Django 6.0.5 on 2026-06-14 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('HR', 'HR Staff'), ('ACCOUNTANT', 'Accountant'), ('SUPERINTENDENT', 'Superintendent'), ('TEACHING', 'Teaching Staff'), ('NON_TEACHING', 'Non-Teaching Staff'), ('ADMINISTRATIVE', 'Administrative Staff')], default='TEACHING', max_length=20),
        ),
    ]
