# Generated by Django 6.0.5 on 2026-06-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_attendance_date_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='loans',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='pagibig',
            field=models.DecimalField(decimal_places=2, default='100.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='philhealth',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='sss',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='tax',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
