# Generated by Django 6.0.5 on 2026-06-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_payroll_loans_alter_payroll_pagibig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='ipcrf_file',
            field=models.FileField(blank=True, null=True, upload_to='ipcrf_uploads/'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='behavior_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='punctuality_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='quality_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
